### ISSUE TITLE
Page editor broken with latest version of Next?

### ISSUE THREAD

**Issue by DavidPIsaac** [LiveDuo/destack#54]
Followed install instructions except used 'npx create-next-app@latest'.
Dragging a component from the picker to a page places an image of the component instead of the component.
Please advise.  Thx.

**Comment by ARMBouhali** [comment]
I confirm the same issue happening.
I used the recommended method for new next projects (i.e. by cloning [destack-starter](https://github.com/liveduo/destack-starter)

**Comment by sergor5** [comment]
Even the starter pack still has the same issue

**Comment by sergor5** [comment]
Just tested [destack-react-starter](https://github.com/Battlelamb/destack-react-starter) and it works

**Comment by ARMBouhali** [comment]
@sergor5 in destack-starter's `package.json` I have

    "next": "12.2.0"
The bug dates from yesterday for me.

Should we use [destack-react-starter](https://github.com/Battlelamb/destack-react-starter) instead ?

**Comment by sergor5** [comment]
I've found what causes the issue:
- installing `destack` as it's shown in the docs through `npm i destack` or `yarn add destack` causes it to install the version `^1.0.3`, while we need to use the version `^0.12.0.`
- also [destack-starter](https://github.com/liveduo/destack-starter) uses the version `^1.0.3` too (which causes the problem), while [destack-react-starter](https://github.com/Battlelamb/destack-react-starter) uses  the version `^0.12.0.`  by default.

Shortly, for it to work now, install destack this way:
- `npm i destack@^0.12.0`
or
- `yarn add destack@^0.12.0`

**Comment by sergor5** [comment]
Found a better solution:
just install `grapesjs`   😅 and then it starts working with the latest `destack`(currently `destack@^1.0.3`)

`npm i grapesjs`
or
`yarn add grapesjs`

**Comment by sergor5** [comment]
Btw latest vesion `grapesjs` breaks some CSS in `destack`. The version `0.17.29` is the latest one that works properly.

So install it like:
`npm i grapesjs@0.17.29`
or
`yarn add grapesjs@0.17.29`

**Comment by sergor5** [comment]
Update:
`destack@^1.0.3` doesn't work with `grapesjs` under version `0.18.1`, so version `0.17.29` won't work.
It works fine if the vesion `grapesjs` is `0.18.1` or above
but has CSS issues like: 
<img width="704" alt="image" src="https://user-images.githubusercontent.com/29211821/200810595-c2854626-efef-4fa6-921a-15bb639a878a.png">


<img width="706" alt="image" src="https://user-images.githubusercontent.com/29211821/200810705-91270ec7-3e82-4213-a35a-af7a93530814.png">

**Comment by sergor5** [comment]
`grapesjs@0.16.45` works with `destack@1.0.3`

**Comment by ARMBouhali** [comment]
@sergor5 Thank you for the quick feedback.
I prefer waiting for next@13 to be supported to future-proof my new project.

**Comment by ARMBouhali** [comment]
@sergor5 Thank you for the quick feedback.
I prefer waiting for next@13 to be supported to future-proof my new project.

**Comment by sergor5** [comment]
after some adjustments in CSS, `destack@^1.0.3 + grapesjs@^0.20.1 + next@^13.0.2` works good enough.

`npm i destack@^1.0.3 grapesjs@^0.20.1`
or
`yarn add destack@^1.0.3 grapesjs@^0.20.1`

Just add this CSS to file `globals.css`.

```css

html,
body {
  padding: 0;
  margin: 0;
} 

.gjs-layer-caret{
  top: 4px !important;
  transform: none !important;
}

.gjs-category-title, .gjs-layer-title, .gjs-block-category .gjs-title, .gjs-sm-sector .gjs-sm-title, .gjs-clm-tags .gjs-sm-title {
  font-weight: lighter;
  background-color: rgba(0,0,0,.1);
  letter-spacing: 1px;
  padding: 9px 10px 9px 20px;
  border-bottom: 1px solid rgba(0,0,0,.25);
  text-align: left;
  position: relative;
  cursor: pointer;
}

.gjs-sm-sector #gjs-sm-caret, .gjs-clm-tags #gjs-sm-caret {
  padding-right: 5px;
  font-size: 11px;
}
.gjs-toolbar-item {
  padding: 5px 7px !important;
  font-size: .8rem;
  cursor: pointer;
  width: 26px;
  vertical-align: middle;
  display: inline-block;
}

.gjs-sm-sector .gjs-sm-property .gjs-sm-layer #gjs-sm-preview, .gjs-clm-tags .gjs-sm-property .gjs-sm-layer #gjs-sm-preview, .gjs-sm-sector .gjs-sm-property .gjs-sm-layer #gjs-sm-preview-box, .gjs-clm-tags .gjs-sm-property .gjs-sm-layer #gjs-sm-preview-box {
  border-radius: 2px;
}

.gjs-sm-sector .gjs-sm-property .gjs-sm-layer>#gjs-sm-preview-box, .gjs-clm-tags .gjs-sm-property .gjs-sm-layer>#gjs-sm-preview-box {
  height: 15px;
  position: absolute;
  right: 27px;
  top: 6px;
  width: 15px;
}

.gjs-sm-sector .gjs-sm-property .gjs-sm-layer>#gjs-sm-preview-box #gjs-sm-preview, .gjs-clm-tags .gjs-sm-property .gjs-sm-layer>#gjs-sm-preview-box #gjs-sm-preview {
  background-color: #fff;
  height: 100%;
  width: 100%;
  background-size: cover !important;
}

.gjs-sm-sector .gjs-sm-property .gjs-sm-layer #gjs-sm-close-layer, .gjs-clm-tags .gjs-sm-property .gjs-sm-layer #gjs-sm-close-layer {
  display: block;
  font-size: 23px;
  position: absolute;
  cursor: pointer;
  right: 5px;
  top: 0;
  opacity: .5;
  filter: alpha(opacity=50);
}

.gjs-sm-sector .gjs-sm-property .gjs-sm-layer, .gjs-clm-tags .gjs-sm-property .gjs-sm-layer {
  background-color: rgba(255,255,255,.055);
  border-radius: 2px;
  margin: 2px 0;
  padding: 7px;
  position: relative;
  cursor: pointer;
}

.gjs-checker-bg, .gjs-field-colorp-c, .checker-bg, .gjs-sm-sector .gjs-sm-property .gjs-sm-layer>#gjs-sm-preview-box, .gjs-clm-tags .gjs-sm-property .gjs-sm-layer>#gjs-sm-preview-box {
  background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAIAAADZF8uwAAAAGUlEQVQYV2M4gwH+YwCGIasIUwhT25BVBADtzYNYrHvv4gAAAABJRU5ErkJggg==");
}

.gjs-sm-sector .gjs-sm-stack #gjs-sm-add, .gjs-clm-tags .gjs-sm-stack #gjs-sm-add {
  padding: 1px 6px !important;
  width: revert;
  height:revert;
  font-size: 22px !important;
  top: -22px !important;
}

.gjs-sm-sector .gjs-sm-field, .gjs-clm-tags .gjs-sm-field, .gjs-sm-sector .gjs-clm-select, .gjs-clm-tags .gjs-clm-select, .gjs-sm-sector .gjs-clm-field, .gjs-clm-tags .gjs-clm-field {
  width: 100%;
  position: relative;
  display: block !important;
}

.gjs-sm-sector .gjs-sm-field input, .gjs-clm-tags .gjs-sm-field input, .gjs-sm-sector .gjs-clm-select input, .gjs-clm-tags .gjs-clm-select input, .gjs-sm-sector .gjs-clm-field input, .gjs-clm-tags .gjs-clm-field input, .gjs-sm-sector .gjs-sm-field select, .gjs-clm-tags .gjs-sm-field select, .gjs-sm-sector .gjs-clm-select select, .gjs-clm-tags .gjs-clm-select select, .gjs-sm-sector .gjs-clm-field select, .gjs-clm-tags .gjs-clm-field select {
    color: #6366f1 !important;
    background-color: #dddada !important;
}

.gjs-sm-layer.gjs-sm-active {
  background-color: rgb(72 72 72 / 12%) !important;
}

```
